"""add employee email

Revision ID: b482a98600fa
Revises: 0002_sadmin_app_type
Create Date: 2026-06-30 22:15:48.139526
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = 'b482a98600fa'
down_revision = '0002_sadmin_app_type'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=True))
        batch_op.alter_column('gender',
               existing_type=postgresql.ENUM('male', 'female', 'transgender', name='gender_enum'),
               nullable=True)
        batch_op.alter_column('designation',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('employment_type',
               existing_type=postgresql.ENUM('P', 'T', 'FT', 'B', name='employment_type_enum'),
               nullable=True)
        batch_op.alter_column('pay',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_employees_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_employees_mobile_number'), ['mobile_number'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employees_mobile_number'))
        batch_op.drop_index(batch_op.f('ix_employees_email'))
        batch_op.alter_column('pay',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
        batch_op.alter_column('employment_type',
               existing_type=postgresql.ENUM('P', 'T', 'FT', 'B', name='employment_type_enum'),
               nullable=False)
        batch_op.alter_column('designation',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('gender',
               existing_type=postgresql.ENUM('male', 'female', 'transgender', name='gender_enum'),
               nullable=False)
        batch_op.drop_column('email')

    # ### end Alembic commands ###
